### PR TITLE
Asciidocsy

### PR DESCRIPTION
**Pull request by capsulecorplab**
Allows for building with [asciidocsy](https://asciidocsy.netlify.app/about) theme with support for:

- asciidoctor-diagram
- asciidoctor-pdf
- asciidoctor-revealjs
- asciidoctor-html5s

Uses [ruby-2.6-buster](https://github.com/docker-library/ruby/blob/761ae37f67acc54d49f085dc4e5a2443a77700e6/2.6/buster/Dockerfile) as base image

### CODE REVIEW

**Comment by capsulecorplab** [comment]
There are two options for testing the docker image locally,

**Option 1:**

Clone the [asciidocsy](https://github.com/DocOps/asciidocsy-jekyll-theme) repo, `cd` into repo, then run the docker image for running the Jekyll server - this will pull the [asciidoctor-extended:asciidocsy](https://hub.docker.com/repository/registry-1.docker.io/capsulecorplab/asciidoctor-extended/builds/15d393a0-9023-4d7b-bfc3-1e37e3f748b5) docker image from DockerHub:
```
docker run --rm --volume="$PWD:/src" -w "/src" -p 4000:4000 capsulecorplab/asciidoctor-extended:asciidocsy 'jekyll serve --host 0.0.0.0'
```

**Option 2:**

Clone the [asciidoctor-extended](https://github.com/capsulecorplab/asciidoctor-extended) repo, `cd` into repo, and build a local docker image:
```
docker build -t asciidoctor-extended:Dockerfile .
```

then, clone the [asciidocsy](https://github.com/DocOps/asciidocsy-jekyll-theme) repo, `cd` into repo, `git checkout asciidocsy`, then run the Jekyll server from the locally built docker image:
```
docker run --rm --volume="$PWD:/src" -w "/src" --env JEKYLL_ENV=production -p 4000:4000 n asciidoctor-extended:Dockerfile 'jekyll serve --host 0.0.0.0'
```

**Comment by capsulecorplab** [comment]
There are two options for testing the docker image locally,

**Option 1:**

Clone the [asciidocsy](https://github.com/DocOps/asciidocsy-jekyll-theme) repo, `cd` into repo, then run the docker image for running the Jekyll server - this will pull the [asciidoctor-extended:asciidocsy](https://hub.docker.com/repository/registry-1.docker.io/capsulecorplab/asciidoctor-extended/builds/15d393a0-9023-4d7b-bfc3-1e37e3f748b5) docker image from DockerHub:
```
docker run --rm --volume="$PWD:/src" -w "/src" -p 4000:4000 capsulecorplab/asciidoctor-extended:asciidocsy 'jekyll serve --host 0.0.0.0'
```

**Option 2:**

Clone the [asciidoctor-extended](https://github.com/capsulecorplab/asciidoctor-extended) repo, `cd` into repo, `git checkout asciidocsy`, and build a local docker image:
```
docker build -t asciidoctor-extended:Dockerfile .
```

then, clone the [asciidocsy](https://github.com/DocOps/asciidocsy-jekyll-theme) repo, `cd` into repo, then run the Jekyll server from the locally built docker image:
```
docker run --rm --volume="$PWD:/src" -w "/src" --env JEKYLL_ENV=production -p 4000:4000 n asciidoctor-extended:Dockerfile 'jekyll serve --host 0.0.0.0'
```

**Comment by capsulecorplab** [comment]
Site is deployed using [asciidoctor-extended:asciidocsy](https://hub.docker.com/repository/registry-1.docker.io/capsulecorplab/asciidoctor-extended/builds/15d393a0-9023-4d7b-bfc3-1e37e3f748b5) docker image to https://capsulecorplab.github.io/asciidocsy-jekyll-theme/ via [deploy branch, forked from trunk-0.2.0](https://github.com/capsulecorplab/asciidocsy-jekyll-theme/tree/deploy) branch, but page isn't building correctly. Will, rebase [deploy branch, forked from trunk-0.2.0](https://github.com/capsulecorplab/asciidocsy-jekyll-theme/tree/deploy) off https://github.com/DocOps/asciidocsy-jekyll-theme/pull/53 once merged, then attempt to rebuild

**Comment by capsulecorplab** [comment]
Deployed https://github.com/capsulecorplab/asciidocsy-jekyll-theme/actions/runs/1037629380 after rebasing off https://github.com/DocOps/asciidocsy-jekyll-theme/commit/880e85d8f7a40bcd5b1627aaecc35fb7f6474ea9, but still appears to be experiencing page formatting issues with build

**Comment by briandominick** [comment]
I finally had another chance today to take a look at this, but I really don't know enough about Docker I guess. I have not run into these errors before, but I had to install Docker on this fairly new machine to try this a couple of weeks ago, and I still must be missing something.

I am following the instructions here, but I consistently get errors about this daemon:

```
docker build -t asciidoctor-extended:Dockerfile .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=asciidoctor-extended%3ADockerfile&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied

``` 

I never use Docker ironically because I'm always on Linux. This box is Fedora 34, Docker version 20.10.7, build f0df350.

**Comment by briandominick** [comment]
Lol nevermind `sudo`.

**Pull request merged**
